In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_data = pd.read_csv('./data/raw/manager_matches.csv')

In [7]:
df_data[df_data['date'] == df_data['date'].min()]

,game_id,date,season,competition_id,competition_type,club,opponent,goals_for,goals_against,manager,venue,goal_diff,result,manager_label
1618,2229839,2012-08-11,2012,FR1,domestic_league,Paris Saint-Germain Football Club,Football Club Lorient-Bretagne Sud,2,2,Carlo Ancelotti,home,0,D,Carlo Ancelotti

In [11]:
df_data.sort_values('date', ascending = True).head(5)

,game_id,date,season,competition_id,competition_type,club,opponent,goals_for,goals_against,manager,venue,goal_diff,result,manager_label
1618,2229839,2012-08-11,2012,FR1,domestic_league,Paris Saint-Germain Football Club,Football Club Lorient-Bretagne Sud,2,2,Carlo Ancelotti,home,0,D,Carlo Ancelotti
897,2244382,2012-08-19,2012,ES1,domestic_league,Real Madrid Club de Fútbol,Valencia Club de Fútbol S. A. D.,1,1,José Mourinho,home,0,D,José Mourinho
1827,2229846,2012-08-19,2012,FR1,domestic_league,Paris Saint-Germain Football Club,AC Ajaccio,0,0,Carlo Ancelotti,away,0,D,Carlo Ancelotti
0,2251270,2012-08-26,2012,IT1,domestic_league,Associazione Calcio Milan,UC Sampdoria,0,1,Massimiliano Allegri,home,-1,L,Massimiliano Allegri
1066,2242834,2012-08-26,2012,ES1,domestic_league,Real Madrid Club de Fútbol,Getafe Club de Fútbol S. A. D. Team Dubai,1,2,José Mourinho,away,-1,L,José Mourinho